app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

images:
    type:     rest
    resource: AppBundle\Controller\ImageController

categories:
    type:     rest
    resource: AppBundle\Controller\CategoryController

tags:
    type:     rest
    resource: AppBundle\Controller\TagController
    
roles:
    type:     rest
    resource: AppBundle\Controller\RoleController
    
users:
    type:     rest
    resource: AppBundle\Controller\UserController

themes:
    type:     rest
    resource: AppBundle\Controller\ThemeController